name: atoupic
description: A belote card game

version: 0.0.1+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: ^0.18.1
  kiwi: ^0.2.0
  equatable: ^1.0.1
  collection: ^1.14.11
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.7.2
  kiwi_generator: ^0.4.0
  flutter_launcher_icons: ^0.7.3
  test: ^1.3.0
  bloc_test: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cards/clubs/7.png
    - assets/images/cards/clubs/8.png
    - assets/images/cards/clubs/9.png
    - assets/images/cards/clubs/10.png
    - assets/images/cards/clubs/A.png
    - assets/images/cards/clubs/J.png
    - assets/images/cards/clubs/K.png
    - assets/images/cards/clubs/Q.png
    - assets/images/cards/diamonds/7.png
    - assets/images/cards/diamonds/8.png
    - assets/images/cards/diamonds/9.png
    - assets/images/cards/diamonds/10.png
    - assets/images/cards/diamonds/A.png
    - assets/images/cards/diamonds/J.png
    - assets/images/cards/diamonds/K.png
    - assets/images/cards/diamonds/Q.png
    - assets/images/cards/hearts/7.png
    - assets/images/cards/hearts/8.png
    - assets/images/cards/hearts/9.png
    - assets/images/cards/hearts/10.png
    - assets/images/cards/hearts/A.png
    - assets/images/cards/hearts/J.png
    - assets/images/cards/hearts/K.png
    - assets/images/cards/hearts/Q.png
    - assets/images/cards/spades/7.png
    - assets/images/cards/spades/8.png
    - assets/images/cards/spades/9.png
    - assets/images/cards/spades/10.png
    - assets/images/cards/spades/A.png
    - assets/images/cards/spades/J.png
    - assets/images/cards/spades/K.png
    - assets/images/cards/spades/Q.png
    - assets/images/cards/BackFace.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"