default_platform(:android)

platform :android do
  desc "Deploy to the Internal Test track"
  lane :deploy_internal_test do
    upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
